<a href="https://colab.research.google.com/github/Lacusxx/LinearAlgebra_SecondSem/blob/main/Assignment6_Perona.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE
## Laboratory 6 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

A matrix's transpose is found by reversing its rows into columns or columns into rows. The matrix's transpose is denoted by the letter "T" in the superscript of the provided matrix. For example, if "A" is the given matrix, the matrix's transpose is denoted as $A'$ or $A^T$. Thus, a matrix transpose is described as "A matrix generated by converting all of the rows of a given matrix into columns and vice versa.” 

So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [ ]:
J = np.array([
    [46 ,50, -52],
    [21, 35, 40],
    [84, -42, 69]
])
J

array([[ 46,  50, -52],
       [ 21,  35,  40],
       [ 84, -42,  69]])

In [ ]:
JT = np.transpose(J)
JT

array([[ 46,  21,  84],
       [ 50,  35, -42],
       [-52,  40,  69]])

In [ ]:
JT2 = J.T
JT2

array([[ 46,  21,  84],
       [ 50,  35, -42],
       [-52,  40,  69]])

In [ ]:
np.array_equiv(JT1, JT2)

True

In [ ]:
M = np.array([
    [45,72,33,94],
    [15,21,46,28],
])
M.shape

(2, 4)

In [ ]:
np.transpose(M).shape

(4, 2)

In [ ]:
M.T.shape

(4, 2)

## Dot Product / Inner Product

In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [ ]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X @ Y

array([[3, 4],
       [2, 2]])

In [ ]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

When compared to vector dot products, matrix dot products have additional rules. There are fewer constraints because vector dot products have only one dimension. Because we are now dealing with Rank 2 vectors, we must follow the following rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
A = np.array([
    [43, 56],
    [29, -69],
    [90, 56]
])
B = np.array([
    [87,94],
    [67,87],
    [-16,-34]
])
T = np.array([
    [21,15,19],
    [14,21,25]
])
print(A.shape)
print(B.shape)
print(T.shape)

(3, 2)
(3, 2)
(2, 3)


In [ ]:
A @ T

array([[ 1687,  1821,  2217],
       [ -357, -1014, -1174],
       [ 2674,  2526,  3110]])

In [ ]:
B @ T

array([[ 3143,  3279,  4003],
       [ 2625,  2832,  3448],
       [ -812,  -954, -1154]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
A @ B.T

array([[ 9005,  7753, -2592],
       [-3963, -4060,  1882],
       [13094, 10902, -3344]])

In [ ]:
X = np.array([
    [15,27,33,90]
])
Y = np.array([
    [11,20,45,-16]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [ ]:
Y.T @ X

array([[  165,   297,   363,   990],
       [  300,   540,   660,  1800],
       [  675,  1215,  1485,  4050],
       [ -240,  -432,  -528, -1440]])

And you can see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

I'll be doing just one of the properties and I'll leave the rest to test your skills!

In [ ]:
A = np.array([
    [33,21,31],
    [46,53,41],
    [14,21,80]
])
B = np.array([
    [47,19,64],
    [54,61,92],
    [14,43,85]
])
C = np.array([
    [13,12,40],
    [20,15,16],
    [31,60,17]
])

In [ ]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A matrix is a collection of several numbers. For a square matrix, that is, a matrix with the same number of rows and columns, crucial information about the matrix can be captured in a single integer called the determinant. The determinant can be used to solve linear equations, capture how linear transformations alter area or volume, and change variables in integrals.


The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
A = np.array([
    [14,54],
    [70,43]
])
np.linalg.det(A)

-3178.0000000000045

In [ ]:
B = np.array([
    [14,23,45,46],
    [60,54,73,38],
    [34,61,54,42],
    [84,53,56,32]
])
np.linalg.det(B)

1764867.999999999

## Inverse

The reciprocal of a matrix is just the matrix itself, as we do in normal arithmetic when dealing with a single number. Equations can be solved and unknown variables can be determined using this reciprocal. Inverse matrices are those in which the original matrix is multiplied by the inverse matrix and the result is the same. 

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
M = np.array([
    [76,45],
    [75, -35]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 0]])

In [ ]:
N = np.array([
    [54,64,28,43,89,32,4],
    [0,42,81,11,2,76,23],
    [86,9,53,40,75,0,33],
    [16,26,34,82,94,3,31],
    [84,36,68,87,16,62,1],
    [-55,5,32,73,61,80,-50],
    [-32,-75,11,21,16,20,62],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [8.0, 0.6, 0.9],
    [0.2, 0.7, 5.0],
    [0.3, 0.3, 8.0]
])
weights = np.array([
    [0.5, 0.1, 0.8]
])
p_grade = squad @ weights.T
p_grade


array([[4.78],
       [4.17],
       [6.58]])

## Activity

### Task 1


Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
np.array([])

array([], dtype=float64)

##$A \cdot B \neq B \cdot A$


In [ ]:
A = np.array([
        [26,37,63], 
        [45 ,45,36], 
        [65,75,45]
        ])
B = np.array([
        [77,98,49], 
        [48,36,15],
        [66,98,72]
        ])
  
result = [[0 for x in range(3)] for y in range(3)]  
  
 
for i in range(len(B)): 
    for j in range(len(A[0])): 
        for k in range(len(A)): 
  

            result[i][j] += A[i][k] * B[k][j] 

print('A.B IS')
print(result)
print('\n')
  
result = [[0 for x in range(3)] for y in range(3)]  
  
 
for i in range(len(B)): 
    for j in range(len(A[0])): 
        for k in range(len(A)): 
  

            result[i][j] += B[i][k] * A[k][j] 
  
print('B.A IS')
print(result)
print('\n')
print('Therefore A.B is not equalt to B.A')

A.B IS
[[7936, 10054, 6365], [8001, 9558, 5472], [11575, 13480, 7550]]


B.A IS
[[9597, 10934, 10584], [3843, 4521, 4995], [10806, 12252, 10926]]


Therefore A.B is not equalt to B.A


##$A \cdot (B \cdot C) = (A \cdot B) \cdot C$


In [ ]:
A = np.array ([
      [32,45,65],
      [3,5,76],
      [12,56,98]
      ])
B = np.array ([
      [12,67,3],
      [76,83,90],
      [23,454,1]
      ])
C = np.array ([
      [1,76,98],
      [23,45,77],
      [98,45,77]
      ])


result = np.dot(B,C)
result = np.dot(A,result);
print("A.(B.C) is")
for r in result:
 print(r)
print('\n')
result = np.dot(A,B)
result = np.dot(result,C);
print("(A.B).C) is")
for r in result:
 print(r)
print('Therefore A.(B.C) = (A.B).C)')

A.(B.C) is
[1231924 2184724 3568502]
[ 862354 1768939 2957507]
[1662418 2986014 4896178]


(A.B).C) is
[1231924 2184724 3568502]
[ 862354 1768939 2957507]
[1662418 2986014 4896178]


##$A\cdot(B+C) = A\cdot B + A\cdot C$


In [ ]:
A = np.array ([
      [45,54,32],
      [65,8,21],
      [98,12,43]
      ])
B = np.array ([
      [87,53,13],
      [54,76,31],
      [21,54,75]
      ])
C = np.array ([
      [31,76,43],
      [87,53,31],
      [87,53,13]
      ])

result = [[B[i][j] + C[i][j]  for j in range
(len(B[0]))] for i in range(len(B))]
result = np.dot(A,result)
print("A.(B+C) is")
for r in result:
 print(r)
print('\n')
result = np.dot(A,B)
result1 = np.dot(A,C)
result = [[result[i][j] + result1[i][j]  for j in range
(len(result[0]))] for i in range(len(result))]
print("A.B+A.C) is")
for r in result:
 print(r)
print('\n')
print('Therfore A.(B+C) = A.B+A.C)')


A.(B+C) is
[16380 16195  8684]
[11066 11664  5984]
[17900 18791 10016]


A.B+A.C) is
[16380, 16195, 8684]
[11066, 11664, 5984]
[17900, 18791, 10016]


Therfore A.(B+C) = A.B+A.C)


##$(B+C)\cdot A = B\cdot A + C\cdot A$


In [ ]:
A = np.array ([
      [43,65,23],
      [5,7,8],
      [87,5,33]
      ])
B = np.array ([
      [67,7,23],
      [76,98,32],
      [34,71,1]
      ])
C = np.array ([
      [56,872,3],
      [53,76,32],
      [54,87,34]
      ])

result = [[B[i][j] + C[i][j]  for j in range
(len(B[0]))] for i in range(len(B))]
result = np.dot(result,A)
print("A.(B+C) is")
for r in result:
 print(r)
print('\n')
result = np.dot(B,A)
result1 = np.dot(C,A)
result = [[result[i][j] + result1[i][j]  for j in range
(len(result[0]))] for i in range(len(result))]
print("(A.B)+(A.C) is")
for r in result:
 print(r)
print('\n')
print('Therefore A.(B+C) = (A.B)+(A.C)')

A.(B+C) is
[11946 14278 10719]
[11985  9923  6471]
[7619 7001 4443]


(A.B)+(A.C) is
[11946, 14278, 10719]
[11985, 9923, 6471]
[7619, 7001, 4443]


Therefore A.(B+C) = (A.B)+(A.C)


##$A\cdot I = A$


In [ ]:
M1 = np.array([
        [54,76,35], 
        [35,13,76], 
        [8,5,8]
        ])
M2 = np.array([
        [1,0,0], 
        [0,1,0],
        [0,0,1]
        ])
  
result = [[0 for x in range(3)] for y in range(3)]  
  
 
for i in range(len(M2)): 
    for j in range(len(M1[0])): 
        for k in range(len(M1)): 
  

            result[i][j] += M2[i][k] * M1[k][j] 
  
print(result)
print('\n')
print('Therefore A.I = A')

[[54, 76, 35], [35, 13, 76], [8, 5, 8]]


Therefore A.I = A


##$A\cdot \emptyset = \emptyset$ 

In [ ]:
M1 = np.array([
        [45,65,3], 
        [65,25,7], 
        [12,76,43]
        ])
M2 = np.array([
        [0,0,0], 
        [0,0,0],
        [0,0,0]
        ])
  
result = [[0 for x in range(3)] for y in range(3)]  
  
 
for i in range(len(M2)): 
    for j in range(len(M1[0])): 
        for k in range(len(M1)): 
  

            result[i][j] += M2[i][k] * M1[k][j] 
  
print(result)
print('\n')
print('Therefore A.\u03B8 = \u03B8')

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


Therefore A.θ = θ


## Conclusion

###How can matrix operations solve problems in healthcare?
The matrix operations could provide an important framework; by constructing a matrix, care practices can be improved, resulting in a strong relationship between core competencies and quality results. Attitude, knowledge, skills, and so on are examples of core competencies.

The goal of establishing such interaction is to review how each quality outcome is affected by the competencies or skills or other factors, it could solve the problem by putting the related data in the matrices, it would analyze the matrices, next, people would learn about each quality outcome or result, and the factors that influence each quality result, this situation would help users to make important decisions in patient care, and this could bring significant changes b Furthermore, such matrices would be valuable for health care education. People in healthcare would have more opportunities to conduct research, and the healthcare system would be more operationally efficient.

