<a href="https://colab.research.google.com/github/Lacusxx/LinearAlgebra_SecondSem/blob/main/PERONA_Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for CHE
##Laboratory 2 : Matrices

###Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.



#Discussion


In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline 

###Matrices


The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have $A$ and $B$ as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        4x+2y-3z \\ 
        31x -45y -18z \\
        -45x + 1y +5z
    \end{array}
\right. $$


:$$
A=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix} \\
C=\begin{bmatrix} 4 & 2 & -3 \\ 31 &-45 & -18 \\ -45 & 1 & 5\end{bmatrix} \\
$$


Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices.
And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by aixj.Denoted by i is the number of rows in the matrix while $j$ stands for the number of columns. Do note that the size of a matrix is $i$ x $j$.

$$
A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
  print(f'matrix:\n{matrix}\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')


In [ ]:
## Deaclaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

matrix:
[[1 2]
 [3 1]]
Shape:	(2, 2)
Rank:	2



In [ ]:
T = np.array([
    [1, 2, 4],
    [3, 1, 5]
])
describe_mat(T)

matrix:
[[1 2 4]
 [3 1 5]]
Shape:	(2, 3)
Rank:	2



In [ ]:
H = np.array([6,7,8,9,10])



describe_mat(H)

matrix:
[ 6  7  8  9 10]
Shape:	(5,)
Rank:	1



In [ ]:
j = np.array([2,25,20,20])



describe_mat(j)

matrix:
[ 2 25 20 20]
Shape:	(4,)
Rank:	1



#Categorizing Matrices


##According to Shape

###Row and Column Matrices


In mathematics, a row matrix is a form of matrix with a single row.

In [ ]:
row_mat_1D = np.array([
    0, 9, 0, 4
])

row_mat_2D = np.array([
    [0, 2, 2, 5]
])
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

matrix:
[0 9 0 4]
Shape:	(4,)
Rank:	1

matrix:
[[0 2 2 5]]
Shape:	(1, 4)
Rank:	2



A single-column matrix is referred to as a column matrix. The column matrix's order is represented by m x 1, therefore each row will contain a single element arranged in such a way that it represents a column.

In [ ]:
column_mat = np.array([
    [1],
    [3],
    [67]
])
describe_mat(column_mat)

matrix:
[[ 1]
 [ 3]
 [67]]
Shape:	(3, 1)
Rank:	2



###Square Matrices

A square matrix is a matrix with the same number of rows and columns on both sides. The square matrix of order m is known as the m m matrix in mathematics. 

In [ ]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0]== matrix.shape[1] else False
  print(f'matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
squarematrix = np.array([
  [1,2,3],
  [3,6,9],
  [3,5,67]
])

disqaure = np.array([
  [2,21],
  [4,5],
  [64,78]
])

describe_mat(squarematrix)
describe_mat(disqaure)

matrix:
[[ 1  2  3]
 [ 3  6  9]
 [ 3  5 67]]

Shape:	(3, 3)
Rank:	2
Is Square: True

matrix:
[[ 2 21]
 [ 4  5]
 [64 78]]

Shape:	(3, 2)
Rank:	2
Is Square: False



##According to Element Value


###Null Matrix

A Null Matrix is a matrix with no elements. It is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0]== matrix.shape[1] else False
    print(f'matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else:
    print('Matrix is Null')

In [ ]:
nullmatrix = np.array ([])
describe_mat(nullmatrix)

Matrix is Null


###Zero Matrix

A zero matrix is a square matrix in which all of the elements are zero (0).

In [ ]:
zeroM_row = np.zeros ((1,2))
zeroM_square = np.zeros ((4,4))
zeroM_rectangle = np.zeros ((5,3))

print(f'Zero Row Matrix: \n{zeroM_row}')
print(f'Zero Square Matrix: \n{zeroM_square}')
print(f'Zero Rectangle Matrix: \n{zeroM_rectangle}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zero Rectangle Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


###Ones Matrix

A matrix of ones, also known as an all-ones matrix, is a matrix in which each member is equal to one.

In [ ]:
onesM_row = np.ones ((1,2))
onesM_square = np.ones ((4,4))
onesM_rectangle = np.ones ((5,3))

print(f'Zero Row Matrix: \n{onesM_row}')
print(f'Zero Square Matrix: \n{onesM_square}')
print(f'Zero Rectangle Matrix: \n{onesM_rectangle}')

Zero Row Matrix: 
[[1. 1.]]
Zero Square Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Zero Rectangle Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


###Diagonal Matrix

Typically, a diagonal matrix is a square matrix of rank n containing values on the main diagonal and zeros on the other diagonals.

In [ ]:
np.array([
  [2,0,0],
  [0,4,0],
  [0,0,6]
])

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

In [ ]:
D = np.diag([2,4,6,12,14,56,78,98,4,45,76,67,69])
D.shape[0] == D.shape[1]
D

array([[ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 14,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 56,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 78,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 98,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 45,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 76,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 67,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 69]])

###Identity Matrix

The identity matrix of size n in linear algebra is the nxn square matrix with ones on the main diagonal and zeros everywhere else.

In [ ]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

###Upper Triangular Matrix

If all of the entries below the main diagonal are zero, a square matrix is called upper triangular.

In [ ]:
np.array([
  [1,5,6,7],
  [0,3,5,8],
  [0,0,9,7],
  [0,0,0,2]
])

array([[1, 5, 6, 7],
       [0, 3, 5, 8],
       [0, 0, 9, 7],
       [0, 0, 0, 2]])

###Lower Triangular Matrix

Similarly, if all of the entries above the main diagonal are zero, a square matrix is called lower triangular.

In [ ]:
X = np.array([
  [1,0,0,0],
  [8,5,0,0],
  [9,6,4,0],
  [2,4,6,8]
])
X

array([[1, 0, 0, 0],
       [8, 5, 0, 0],
       [9, 6, 4, 0],
       [2, 4, 6, 8]])

In [ ]:
H = np.tril(X)
H

array([[1, 0, 0, 0],
       [8, 5, 0, 0],
       [9, 6, 4, 0],
       [2, 4, 6, 8]])

##Matrix Algebra

ADDITION

To be added, two matrices must have the same amount of rows and columns. The sum of two matrices A and B, in this situation, will be a matrix with the same number of rows and columns as A and B. By adding the appropriate elements of A and B, the sum of A and B, denoted A + B, is obtained.


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

R = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

G+R

array([[ 2, 14, 16],
       [ 4,  4,  4],
       [ 8, 12, 14]])

In [ ]:
2+G

array([[ 3,  9, 10],
       [ 4,  4,  4],
       [ 6,  8,  9]])

SUBTRACTION

Matrix subtraction is very much like addition. Subtraction between two matrices is achievable if their order or dimensions are the same.

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

R = np.array([
    [5,7,8],
    [2,6,2],
    [2,6,8]
])

G-R

array([[-4,  0,  0],
       [ 0, -4,  0],
       [ 2,  0, -1]])

In [ ]:
5-R

array([[ 0, -2, -3],
       [ 3, -1,  3],
       [ 3, -1, -3]])

ELEMENT-WISE MULTIPLICATION

Every element of the first matrix is multiplied by the corresponding element of the second matrix in element-wise matrix multiplication.

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

R = np.array([
    [5,7,8],
    [2,6,2],
    [2,6,8]
])

G*R

array([[ 5, 49, 64],
       [ 4, 12,  4],
       [ 8, 36, 56]])

In [ ]:
19*R

array([[ 19, 133, 152],
       [ 38,  38,  38],
       [ 76, 114, 133]])

ACTUAL MULTIPLICATION

When multiplying two matrices, the first matrix's column count must equal the second matrix's row count. The result will have the same number of rows as the first matrix and the same number of columns as the second matrix.   


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

R = np.array([
    [5,7,8],
    [2,6,2],
    [2,6,8]
])

G@R

array([[ 35,  97,  86],
       [ 18,  38,  36],
       [ 46, 106, 100]])

## PRACTICE

1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$

$$
\theta=\begin{bmatrix} 5 & 3 & -1 \end{bmatrix} \\
$$

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

In [ ]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0]== matrix.shape[1] else False
  print(f'matrix:\n{matrix}\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
A = np.array([
    [1,2,1],
    [0,4,-1],
    [0,0,10]
])
describe_mat(A)

matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]
Shape:	(3, 3)
Rank:	2
Is Square: True



3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

$$
G = \left\{
    \begin{array}\
        a + 7b + 8c \\ 
        2a + 2b + 2c \\
        4a + 6b + 7c
    \end{array}
\right. $$


$$
G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7 \end{bmatrix} \\
$$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

$$
H =\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7 \end{bmatrix} \\
$$

$$
H = \left\{
    \begin{array}\
        a \\ 
        2a + 2b \\
        4a + 6b + 7c
    \end{array}
\right. $$

##TASK 1


Create a function named mat_desc() that throughly describes a matrix, it should:

  1. Displays the shape, size, and rank of the matrix.
  2. Displays whether the matrix is square or non-square.
  3. Displays whether the matrix is an empty matrix.
  4. Displays if the matrix is an identity, ones, or zeros matrix
  
Use 3 sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [4]:
def mat_desc(mat):
   sq = False
   mat = np.array(mat)
   print(mat)
   print('Shape:', mat.shape)
   print('Size:', mat.size)
   print('Rank:', np.linalg.matrix_rank(mat))
   if(mat.shape[0] == mat.shape[1]):
       sq = True
       print('The matrix is square')
   else:
       print('The matrix is non-square')
   if(mat.shape[0] == 0 and mat.shape[1] == 0):
       print('The matrix is empty')
   else:
       print('The matrix is not empty')
   iden = np.identity(mat.shape[0])
   if(sq and (iden == mat).all()):
       print('The matrix is an identity matrix')
   else:
       print('The matrix is not an identity matrix')
   one = np.ones((mat.shape[0], mat.shape[1]))
   if((one == mat).all()):
       print('The matrix is a ones matrix')
   else:
       print('The matrix is not a ones matrix')
   zero = np.zeros((mat.shape[0], mat.shape[1]))
   if((zero == mat).all()):
       print('The matrix is a zeros matrix')
   else:
       print('The matrix is not a zeros matrix')



In [5]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

mat_desc(G)

[[1 7 8]
 [2 2 2]
 [4 6 7]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not a ones matrix
The matrix is not a zeros matrix


In [6]:
A = np.array([
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0]
])

mat_desc(A)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Shape: (4, 4)
Size: 16
Rank: 0
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not a ones matrix
The matrix is a zeros matrix


In [7]:
F = np.array([
    [1,1,1,1,1,1,1],
    [1,1,1,1,1,1,1],
    [1,1,1,1,1,1,1],
    [1,1,1,1,1,1,1],
    [1,1,1,1,1,1,1],
    [1,1,1,1,1,1,1],
    [1,1,1,1,1,1,1],
    [1,1,1,1,1,1,1],
    [1,1,1,1,1,1,1],
    [1,1,1,1,1,1,1],
    [1,1,1,1,1,1,1],
    [1,1,1,1,1,1,1]
    
])

mat_desc(F)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]
Shape: (12, 7)
Size: 84
Rank: 1
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is a ones matrix
The matrix is not a zeros matrix


## TASK 2

Create a function named mat_operations() that takes in two matrices a input parameters it should:

Determines if the matrices are viable for operation and returns your own error message if they are not viable.
  1. Returns the sum of the matrices.
  2. Returns the differen of the matrices.
  3. Returns the element-wise multiplication of the matrices.
  4. Returns the element-wise division of the matrices.
  
Use 3 sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [8]:
def mat_operations(mat1, mat2):
    mat1 = np.array(mat1)
    mat2 = np.array(mat2)
    print('Matrix 1:\n', mat1)
    print('Matrix 2:\n', mat2)
    if(mat1.shape != mat2.shape):
        print('I apoligize. I could not perform operations. The shape of your given matrices are not for this code.')
        return
    print('Sum of the given matrices:')
    msum = mat1 + mat2
    print(msum)
    print('Difference of the given matrices:')
    mdiff = mat1 - mat2
    print(mdiff)
    print('Element-wise multiplication of the given matrices:')
    mmul = mat1*mat2
    print(mmul)
    print('Element-wise division of the given matrices:')
    mmul = mat1/mat2
    print(mmul)

In [9]:
mat1 = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

mat2 = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

mat_operations(mat1, mat2)

Matrix 1:
 [[1 7 8]
 [2 2 2]
 [4 6 7]]
Matrix 2:
 [[1 7 8]
 [2 2 2]
 [4 6 7]]
Sum of the given matrices:
[[ 2 14 16]
 [ 4  4  4]
 [ 8 12 14]]
Difference of the given matrices:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Element-wise multiplication of the given matrices:
[[ 1 49 64]
 [ 4  4  4]
 [16 36 49]]
Element-wise division of the given matrices:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
mat1 = np.array([
    [4,5,76],
    [34,654,76]
])

mat2 = np.array([
    [6,8,6],
    [82,6,12],
    [3,78,32]
])

mat_operations(mat1, mat2)

Matrix 1:
 [[  4   5  76]
 [ 34 654  76]]
Matrix 2:
 [[ 6  8  6]
 [82  6 12]
 [ 3 78 32]]
I apoligize. I could not perform operations. The shape of your given matrices are not for this code.


In [12]:
mat1 = np.array([
  [1,0,0,0],
  [8,5,0,0],
  [9,6,4,0],
  [2,4,6,8]
])

mat2 = np.array([
  [1,5,6,7],
  [0,3,5,8],
  [0,0,9,7],
  [0,0,0,2]
])

mat_operations(mat1, mat2)

Matrix 1:
 [[1 0 0 0]
 [8 5 0 0]
 [9 6 4 0]
 [2 4 6 8]]
Matrix 2:
 [[1 5 6 7]
 [0 3 5 8]
 [0 0 9 7]
 [0 0 0 2]]
Sum of the given matrices:
[[ 2  5  6  7]
 [ 8  8  5  8]
 [ 9  6 13  7]
 [ 2  4  6 10]]
Difference of the given matrices:
[[ 0 -5 -6 -7]
 [ 8  2 -5 -8]
 [ 9  6 -5 -7]
 [ 2  4  6  6]]
Element-wise multiplication of the given matrices:
[[ 1  0  0  0]
 [ 0 15  0  0]
 [ 0  0 36  0]
 [ 0  0  0 16]]
Element-wise division of the given matrices:
[[1.         0.         0.         0.        ]
 [       inf 1.66666667 0.         0.        ]
 [       inf        inf 0.44444444 0.        ]
 [       inf        inf        inf 4.        ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in true_divide


## Conclusion


By utilizing the discussed functions and principles, matrices were given of high importance in this activity. Python is such a well and widely used programming language. It is in high demand all around the world. It can be used in a range of domains, including as machine learning, large data, programming, and app development. By performing this assignment, the students were allowed to practice and understand the ideas, vocabulary, and methodologies of Python. It demands a basic grasp of matrices and their connection to linear calculations, as well as the ability to conduct basic matrix operations and system matrix formulae and processes. Learning the fundamentals unquestionably contributed to the development of one of the many useful and novel traits. It will benefit people in being more logical in their thinking. As an outcome of this course, students will indeed be able to comprehend complicated ideas more simply and solve issues more efficiently. Just like the intricate but effective ways around Python.

